name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/cli-action@v1

      - name: Auto-merge dependabot PRs
        run: |
          gh pr list --state open --author dependabot | while read pr_id _; do
            gh pr merge "$pr_id" --merge --admin
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
